### ISSUE TITLE
Getting a lua error after configuring the plugin for Vim 9.1

### ISSUE THREAD

**Issue by iulianbarbu** [linrongbin16/lsp-progress.nvim#127]
The error I am getting is:
```
.../plugged/lsp-progress.nvim/lua/lsp-progress/defaults.lua:171: attempt to call a nil value (field 'deepcopy')
```

My vimrc contains this setup:
```
lua require('lsp-progress').setup()
```

I have installed lua5.4. Also, in terms of nerd-fonts, I set it up so that `font-patcher` is on the path. I am not sure if this is what the plugin needs or I am totally off.

I am a vim/lua/nerd-fonts newbie, so my questions revolve around:
1. What Lua version is best so that the plugin works for `Vim` too?
2. What exactly should I install for `nerd-fonts`?

**Comment by linrongbin16** [comment]
hi @iulianbarbu ,

1. I didn't design this plugin to work for `Vim`, it's only for `Neovim`. But maybe I can have a try to support `Vim`.
2. The dependencies for `nerd-fonts` is in this line: https://github.com/linrongbin16/lsp-progress.nvim/blob/b673377c50ebaf37053f23cc3caeeb6d469ba1c1/lua/lsp-progress/defaults.lua#L133. It uses the `nf-fa-gear` font in [nerdfonts.com - cheat-sheet](https://www.nerdfonts.com/cheat-sheet) (see below screenshot). I recommend you choose & install one font from [nerd-font](https://www.nerdfonts.com/), and remember to configure the installed font in your terminal (iTerm2 in macOS, Windows Terminal in Windows 10, Gnome Terminal in ubuntu gnome desktop, or kitty/wezterm/alacritty/etc).

<img width="1910" alt="image" src="https://github.com/linrongbin16/lsp-progress.nvim/assets/6496887/3349f793-0d82-4fa3-8dbd-78ef40356d08">

**Comment by iulianbarbu** [comment]
Hi @linrongbin16 ! Thanks for the response and clarifications.

**Comment by linrongbin16** [comment]
hi @iulianbarbu ,

FYI,
In neovim, you still need to install lsp servers, and configure them to make them work.

actually it's not going to be very easy.

Personally I am using below plugins to work with this 'lsp-progress' work:

* [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig): it's a common configuration layer, to help you configure those lsp servers (maybe because there's still some gap between nvim and lsp). this is almost the lsp standard in neovim that you must install.
* [mason.nvim](https://github.com/williamboman/mason.nvim): a plugin to help you manage lsp servers. For example you need clangd for c/c++, pyright for python, etc. you can install them manually and export them to `$PATH` so nvim can see them. But when mason, you can install/upgrade/remove these lsp servers. Mason is like venv to python/pip.
* [none-ls.nvim](https://github.com/nvimtools/none-ls.nvim): Sometimes only lsp server is not enough, because some linters/code formatters/etc are just a shell command, for example clang-format for c/c++, black/yapf for python. So none-ls is using neovim itself as a lsp server, thus transform those formatters/linters message through the LSP protocols.

Hope these introduction helps you enjoy neovim with lsp.
